apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-webapp-testing.fullname" . }}-active
  labels:
    {{- include "golang-webapp-testing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "golang-webapp-testing.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-webapp-testing.fullname" . }}-passive
  labels:
    {{- include "golang-webapp-testing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "golang-webapp-testing.selectorLabels" . | nindent 4 }}
