{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if and .Values.vault .Values.vault.secretPath }}
    avp.kubernetes.io/path: "{{ .Values.vault.secretPath }}"
    {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: <{{ $key }}>
  {{- end }}
{{- end }}
