{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- if and .Values.secret.secretPath }}
    avp.kubernetes.io/path: "{{ .Values.secret.secretPath }}"
    {{- end }}
type: Opaque
stringData:
    {{- toYaml .Values.secret.stringData | nindent 4 }}
{{- end }}
