apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}-clusterip
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}

{{- if .Values.service.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}-nodeport
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if .Values.service.nodePort.port }}
      nodePort: {{ .Values.service.nodePort.port }}
      {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}